sejong-uni/config/urls.py
from django.contrib import admin
from django.urls import path, include
from automl import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('api/', include('rest_framework.urls')),
    path('automl/', include('automl.urls')),
    path('', views.index, name='index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sejong-uni/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
]

sejong-uni/users/models.py
from django.db import models

# Create your models here.

sejong-uni/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

sejong-uni/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from users.forms import UserForm
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.files.storage import default_storage
from django.conf import settings
import os, json


# Create your views here.
def login_view(request):
    return render(request, 'users/login.html')

def logout_view(request):
    logout(request)
    return redirect('index')

def signup_view(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'users/signup.html', {'form': form})

sejong-uni/templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>로그인</title>
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
</head>
<body>
<div class="auth-main">
  <div class="auth-wrapper v3">
    <div class="auth-form">
      <div class="container mt-5">
        <div class="row justify-content-center">
          <div class="col-md-4">
            <div class="card p-4 shadow">
              <h2 class="mb-4 text-center">로그인</h2>
              <form method="post" action="{% url 'users:login' %}">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="username" class="form-label">아이디</label>
                  <input type="text" name="username" class="form-control" id="username" required>
                </div>
                <div class="mb-3">
                  <label for="password" class="form-label">비밀번호</label>
                  <input type="password" name="password" class="form-control" id="password" required>
                </div>
                <button type="submit" class="btn btn-primary w-100">로그인</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>

sejong-uni/templates/users/signup.html
{% extends 'base.html' %}
{% block content %}
{% include "form_errors.html" %}
<div class="auth-main">
  <div class="auth-wrapper v3">
    <div class="auth-form">
      <div class="container mt-5">
        <div class="row justify-content-center">
          <div class="col-md-4">
            <div class="card p-4 shadow">
              <h2 class="mb-4 text-center">회원가입</h2>
              <form method="post" action="{% url 'users:signup' %}">
                {% csrf_token %}
                <div class="form-group mb-3">
                  <label for="username" class="form-label">아이디</label>
                  <input type="text" class="form-control" name="username" id="username"
                         value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class="form-group mb-3">
                  <label for="password1" class="form-label">비밀번호</label>
                  <input type="password" class="form-control" name="password1" id="password1"
                         value="{{ form.password1.value|default_if_none:'' }}">
                </div>
                <div class="form-group mb-3">
                  <label for="password2" class="form-label">비밀번호 확인</label>
                  <input type="password" class="form-control" name="password2" id="password2"
                         value="{{ form.password2.value|default_if_none:'' }}">
                </div>
                <div class="form-group mb-3">
                  <label for="email" class="form-label">이메일</label>
                  <input type="text" class="form-control" name="email" id="email"
                         value="{{ form.email.value|default_if_none:'' }}">
                </div>
                <div class="d-grid mt-3">
                  <button type="submit" class="btn btn-primary">회원가입</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}